"use strict";
// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/communication.proto (package generic, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.CommunicationService = void 0;
const communication_pb_js_1 = require("./communication_pb.js");
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from service generic.CommunicationService
 */
exports.CommunicationService = {
    typeName: "generic.CommunicationService",
    methods: {
        /**
         * @generated from rpc generic.CommunicationService.sendData
         */
        sendData: {
            name: "sendData",
            I: communication_pb_js_1.DataRequest,
            O: communication_pb_js_1.DataResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
    }
};
